export * from './courses/CCourses.constant'
export * from  './galaxy/CGalaxy.constant'
export * from './language/CLanguage.constant'
export * from './menus/CMenuCliente.constant'
export  * from './menus/CMenuManagment.constant'
export * from './planets/CPlanet.constant'
export * from './professor/CProfessor.constant'
export * from './categories/CCategories.constant'